language: python
python:
  - "3.7"  # Or any version you're using
install:
  - pip install -r requirements.txt
script:
  - python manage.py test
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "AKIA5FTZAJ64XCA6D2CH"
  secret_access_key:
    secure: "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"
  region: "us-west-2"
  app: "test3"
  env: "test-env3"
  bucket_name: "the-target-S3-bucket"
YAML
